jQuery(document).ready(function($){$('.wpcf7-submit').each(function(){var $wrapper=$('<div class="submit-button-wrapper"></div>');$(this).wrap($wrapper)});$('.specialize-item').click(function(){if($(this).hasClass('active')){$(this).removeClass('active')}else{$('.specialize-item').removeClass('active');$(this).addClass('active')}
if($('.specialize-item.active').length>0){$('.specialize-list').addClass('active')}else{$('.specialize-list').removeClass('active')}});let typeSplit;function runSplit(){typeSplit=new SplitType(".split-lines",{types:"words"});createAnimation()}
runSplit();let windowWidth=window.innerWidth;window.addEventListener("resize",function(){if(windowWidth!==window.innerWidth){windowWidth=window.innerWidth;typeSplit.revert();runSplit()}});gsap.registerPlugin(ScrollTrigger);function createAnimation(){document.querySelectorAll(".split-lines").forEach((block,index)=>{let tl=gsap.timeline({scrollTrigger:{trigger:block,start:"top center",end:"bottom center",scrub:1}});tl.to(block.querySelectorAll(".word"),{opacity:1,y:0,stagger:0.1,duration:1,ease:'power3.out'})})}
var swiperCasesMain=new Swiper(".swiper_cases_main",{slidesPerView:3,spaceBetween:12,slidesPerGroupSkip:1,navigation:{nextEl:'.swiper_cases_main .arrow-container_next',prevEl:'.swiper_cases_main .arrow-container_prev',},pagination:{el:".swiper_cases_main .swiper-pagination",clickable:!0,},breakpoints:{320:{slidesPerView:1.05,spaceBetween:12},1201:{slidesPerView:3,spaceBetween:12}},})
$('.lottie_button').each(function(){var $this=$(this);var animationPath=$this.data('animation-path');var $animationContainer=$this.find('.lottie-animation')[0];var animation=lottie.loadAnimation({container:$animationContainer,renderer:'svg',loop:!1,autoplay:!1,path:animationPath});$this.on('mouseenter',function(){animation.goToAndPlay(0)});$this.on('mouseleave',function(){animation.stop()})});$('.faq_popup_click').click(function(event){event.preventDefault()
$('.faq_wrapper_popup').addClass('active')})
$('.close_faq').click(function(){$('.faq_wrapper_popup').removeClass('active')})
$('.bg_popup_faq').click(function(){$('.faq_wrapper_popup').removeClass('active')})
$('.discus_popup_click').click(function(event){event.preventDefault();var formItem=$(this).data('form-item');$('input[name="form-item"]').val(formItem);$('.discus_wrapper_popup').addClass('active')});$('.close_discus').click(function(){$('.discus_wrapper_popup').removeClass('active')})
$('.bg_popup_discus').click(function(){$('.discus_wrapper_popup').removeClass('active')})
$('.button_burger_main').click(function(){$('.main_header').toggleClass('active');$('.bg_burger_menu').toggleClass('active')})
$('.bg_burger_menu').click(function(){$('.main_header').removeClass('active');$(this).removeClass('active')})
$('.button_burger_stick').click(function(){$('.header_sticky').toggleClass('active')})
$('.open_faq_item').click(function(){var parent=$(this).parent('.faq-item');if(parent.hasClass('active')){parent.removeClass('active')}else{$('.faq-item').removeClass('active');parent.addClass('active')}});const header=document.querySelector('.header_wrapper_sticky');const headerMain=document.querySelector('.main_header');const activationPoint=120;const header_bg=document.querySelector('.bg_header_hover');function handleScroll(){if(window.scrollY>=activationPoint){header.classList.add('active')}else{header.classList.remove('active');header_bg.classList.remove('active');$('.sub-menu').removeClass('active');headerMain.classList.remove('active')}}
window.addEventListener('scroll',handleScroll);var swiperReview=new Swiper(".swiper_review_main",{slidesPerView:3,spaceBetween:13,keyboard:{enabled:!0,},loop:!0,navigation:{nextEl:'.reviews-container .arrow-container_next',prevEl:'.reviews-container .arrow-container_prev',},pagination:{el:".swiper_review_main .swiper-pagination",},breakpoints:{320:{slidesPerView:1.18,spaceBetween:10},1201:{slidesPerView:3,spaceBetween:13}},})
var weworkSwiper=new Swiper(".wework_swiper",{slidesPerView:4,spaceBetween:0,keyboard:{enabled:!0,},loop:!1,breakpoints:{320:{slidesPerView:1.05,spaceBetween:6},1201:{slidesPerView:4,spaceBetween:0}},pagination:{el:".wework_swiper .swiper-pagination",},})
if($(window).width()<1201){var approachSwiper=new Swiper(".approach_swiper",{spaceBetween:0,keyboard:{enabled:!0,},loop:!1,breakpoints:{320:{slidesPerView:1.05,spaceBetween:6},1201:{slidesPerView:4,spaceBetween:0}},pagination:{el:".approach_swiper .swiper-pagination",},navigation:{nextEl:'.approach_swiper .arrow-container_next',prevEl:'.approach_swiper .arrow-container_prev',},})}
if($(window).width()<1201){var swiperPostsMob=new Swiper(".swiper_posts_mob",{keyboard:{enabled:!0,},loop:!1,breakpoints:{320:{slidesPerView:1.05,spaceBetween:10},1201:{slidesPerView:4,spaceBetween:0}},})}
var swipersReviewDiscus=document.querySelectorAll('.swiper_review_discus');swipersReviewDiscus.forEach(function(swiperElement){var swiperInstance=new Swiper(swiperElement,{loop:!0,autoplay:{delay:4000,disableOnInteraction:!1},breakpoints:{320:{slidesPerView:1,spaceBetween:10},1201:{slidesPerView:1,spaceBetween:0}},navigation:{nextEl:'.swiper_review_discus .arrow-container_next',prevEl:'.swiper_review_discus .arrow-container_prev',}});swiperElement.addEventListener('mouseenter',function(){swiperInstance.autoplay.stop()});swiperElement.addEventListener('mouseleave',function(){swiperInstance.autoplay.start()})});const progressCircle=document.querySelector(".swiper-pagination .swiper-pagination-bullet-active");var swiperProjects=new Swiper(".swiper_projects",{effect:"creative",creativeEffect:{prev:{shadow:!0,translate:[0,0,-400],},next:{translate:["100%",0,0],},},autoplay:{delay:4000,disableOnInteraction:!1},watchSlidesProgress:!0,loop:!0,grabCursor:!0,pagination:{el:".swiper-pagination",},speed:800})
$('.swiper_projects').on('mouseenter',function(){console.log('stop autoplay');swiperProjects.autoplay.stop();$('.swiper_projects').addClass('swiper-paused')})
$('.swiper_projects').on('mouseleave',function(){console.log('start autoplay');swiperProjects.autoplay.start();$('.swiper_projects').removeClass('swiper-paused')})});if($(window).width()>1201){function wrapEachLetter(element){element.innerHTML=element.textContent.replace(/(\S|\s)/g,function(match){if(match===' '){return"<span class='space'>&nbsp;</span>"}else{return"<span>"+match+"</span>"}})}
function duplicateText(){const menuItems=document.querySelectorAll('.menu-item a');menuItems.forEach(menuItem=>{if(!menuItem)return;const originalText=menuItem.innerText;const duplicateElement=document.createElement('div');duplicateElement.className='text is-absolute';duplicateElement.innerText=originalText;menuItem.innerHTML='';const wrapper=document.createElement('div');wrapper.className='text-wrapper';const originalSpan=document.createElement('div');originalSpan.className='text';originalSpan.innerText=originalText;wrapper.appendChild(originalSpan);wrapper.appendChild(duplicateElement);menuItem.appendChild(wrapper);wrapEachLetter(originalSpan);wrapEachLetter(duplicateElement)})}
document.addEventListener('DOMContentLoaded',duplicateText);document.addEventListener('DOMContentLoaded',()=>{const menuItems=document.querySelectorAll('.menu-item a');menuItems.forEach(menuItem=>{const textSpans=menuItem.querySelectorAll('.text');menuItem.addEventListener('mouseenter',()=>{gsap.fromTo(textSpans,{yPercent:0,autoAlpha:1,opacity:1},{opacity:1,duration:0.5,yPercent:-100,autoAlpha:1,ease:"power2.out"})});menuItem.addEventListener('mouseleave',()=>{gsap.fromTo(textSpans,{opacity:1,yPercent:-100,autoAlpha:1},{opacity:1,duration:0.5,yPercent:0,autoAlpha:1,ease:"power2.out"})})})})}
const menuItems=document.querySelectorAll('.menu-item-has-children');const bgMenu=document.querySelector('.bg_header_hover');const mainHeader=document.querySelector('.main_header');let activeSubMenu=null;function handleMenu(){const isMobile=window.matchMedia("(max-width: 1201px)").matches;menuItems.forEach(item=>{if(item.closest('.menu-title-item')){return}
const link=item.querySelector('a');const subMenu=item.querySelector('.sub-menu');const newLink=link.cloneNode(!0);link.parentNode.replaceChild(newLink,link);if(isMobile){newLink.addEventListener('click',(e)=>{const subLink=e.target.closest('.sub-menu a');if(!subLink){e.preventDefault()}
const isActive=subMenu.classList.contains('active');if(isActive){subMenu.classList.remove('active');bgMenu.classList.remove('active');mainHeader.classList.remove('active')}else{if(activeSubMenu){activeSubMenu.classList.remove('active')}
subMenu.classList.add('active');bgMenu.classList.add('active');mainHeader.classList.add('active');activeSubMenu=subMenu}})}else{newLink.addEventListener('mouseenter',()=>{if(activeSubMenu&&activeSubMenu!==subMenu){activeSubMenu.classList.remove('active')}
subMenu.classList.add('active');bgMenu.classList.add('active');mainHeader.classList.add('active');activeSubMenu=subMenu})}})}
handleMenu();window.addEventListener('resize',handleMenu);window.addEventListener('mousemove',(e)=>{if($(window).width()>1201){if(e.clientY>300){if(activeSubMenu){activeSubMenu.classList.remove('active');bgMenu.classList.remove('active');mainHeader.classList.remove('active');activeSubMenu=null}}}});document.addEventListener('DOMContentLoaded',()=>{const lottieElements=document.querySelectorAll('.lottie-animation-thank');lottieElements.forEach(element=>{const lottiePath=element.getAttribute('data-lottie-path');if(lottiePath){lottie.loadAnimation({container:element,renderer:'svg',loop:!0,autoplay:!0,path:lottiePath})}else{console.warn('Lottie path is not specified for an element')}})});jQuery(document).ready(function($){$('.menu-title-item a').on('click',function(e){e.stopPropagation()})})